"""Add Sponsorship

Revision ID: 0da6fc8db6d7
Revises: 99379162619e
Create Date: 2022-10-03 20:15:15.748108

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0da6fc8db6d7"
down_revision = "99379162619e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_sponsorship",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sa_title", sa.String(), nullable=False),
        sa.Column("en_title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("site_sponsorship")
    # ### end Alembic commands ###
