"""Add PasswordResetToken

Revision ID: 403a2d5efeb8
Revises: 5ac51663112f
Create Date: 2022-08-01 08:55:39.322586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "403a2d5efeb8"
down_revision = "5ac51663112f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_password_reset_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_password_reset_tokens_token_hash"),
        "auth_password_reset_tokens",
        ["token_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_password_reset_tokens_user_id"),
        "auth_password_reset_tokens",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_auth_password_reset_tokens_user_id"),
        table_name="auth_password_reset_tokens",
    )
    op.drop_index(
        op.f("ix_auth_password_reset_tokens_token_hash"),
        table_name="auth_password_reset_tokens",
    )
    op.drop_table("auth_password_reset_tokens")
    # ### end Alembic commands ###
