"""Add revision summary

Revision ID: b3cf424f4ce5
Revises: 481c959deb21
Create Date: 2022-07-17 20:07:12.346626

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b3cf424f4ce5"
down_revision = "481c959deb21"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "proof_revisions",
        sa.Column("summary", sa.Text(), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proof_revisions", "summary")
    # ### end Alembic commands ###
