"""Add Page.ocr_bounding_boxes

Revision ID: bc48af5ec2e6
Revises: d5115e972f06
Create Date: 2022-09-02 20:54:09.246860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bc48af5ec2e6"
down_revision = "d5115e972f06"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "proof_pages", sa.Column("ocr_bounding_boxes", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proof_pages", "ocr_bounding_boxes")
    # ### end Alembic commands ###
