"""Add user description

Revision ID: d5115e972f06
Revises: 8624cb8e20dc
Create Date: 2022-08-28 21:04:06.990345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d5115e972f06"
down_revision = "8624cb8e20dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("description", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "description")
    # ### end Alembic commands ###
