"""Add ProjectSponsorship

Revision ID: e22c8a3d348f
Revises: 99379162619e
Create Date: 2022-10-05 08:05:11.286854

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e22c8a3d348f"
down_revision = "99379162619e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_project_sponsorship",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sa_title", sa.String(), nullable=False),
        sa.Column("en_title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("cost_inr", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("site_project_sponsorship")
    # ### end Alembic commands ###
